version: "3.8"

services:
  feed-db:
    image: postgres:16-alpine3.18
    ports:
      - 8002:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: feed
    secrets:
      - db_password
      - db_user

  redis-cache:
    network_mode: "host"
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    restart: always
volumes:
  cache:
    driver: local
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
