version: "3.8"

services:
  feed-db:
    image: postgres:16-alpine3.18
    ports:
      - 8002:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: feed
    secrets:
      - db_password
      - db_user
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
